gemfile: Gemfile.travis
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

rvm:
  - 1.9.2

before_script: "cp config/database.yml.travis config/database.yml; rake db:drop db:create db:migrate"

env:
  - DB=mysql
