script: "rake travis"
before_script:
  - "cp config/database.yml.travis config/database.yml; rake db:create;rake db:migrate"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

rvm:
  - 1.9.3

env:
  - DB=mysql
