bundler_args: --without development 
script:
 - "rake spec cucumber"

rvm:
  - 1.9.2
  - 1.9.3

branches:
  only:
    - master

before_script:
 - "cp config/database.yml.travis config/database.yml"
 - "rake db:setup db:migrate"

env:
  - DB=mysql

