bundler_args: --without development 
script: "bundle exec rake db:create db:migrate spec"

rvm:
  - 1.9.2
  - 1.9.3

branches:
  only:
    - master

before_script:
 - "cp config/database.yml.travis config/database.yml"

env:
  - DB=mysql

