script: "rake travis"
before_script:
  - "cp config/database.yml.travis.${TRAVIS_RUBY_VERSION}.${DB} config/database.yml"
  - "bundle exec rake --trace db:drop db:create db:migrate"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

rvm:
  - 1.9.2
  - 1.9.3
  - jruby-head

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite
